#83 Add Docker Build

diff --git a/.github/workflows/tests-check.yml b/.github/workflows/tests-check.yml
--- a/.github/workflows/tests-check.yml
+++ b/.github/workflows/tests-check.yml
@@ -29,6 +29,16 @@ jobs:
           cache: npm
       - name: Set Database URL
         run: echo "SOURCE_DATABASE_URL=postgresql://postgres:password@localhost:5432/timescaledb" >> scylla-server/.env
+      - name: Set up Docker Compose
+        run: |
+          sudo apt-get -y update
+          sudo apt-get -y install docker-compose
+      - name: Build Docker Compose
+        run: |
+          if ! docker-compose build; then
+            echo "Docker Compose build failed."
+            exit 1  # This will cause the workflow to fail
+          fi
       - name: Start Docker Container
         run: docker-compose up -d
       - name: Run tests
